DoAn/Areas/admin/Models/NhapHang.cs
namespace DoAn.Areas.admin.Models
{
    public class NhapHang
    {
        public int Id { get; set; }
        public int IDGao { get; set; }
        public int soLuongNhap { get; set; }
        public DateTime ngayNhap { get; set; }
        public Gao gao { get; set; }
    }
}

DoAn/Areas/admin/Controllers/NhapHangController.cs
using Microsoft.AspNetCore.Mvc;

namespace DoAn.Areas.admin.Controllers
{
    [Area("admin")]
    public class NhapHangController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Update()
        {
            return View();
        }
    }
}

DoAn/Areas/admin/Views/NhapHang/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/admin/Views/Share/_layoutAdmin.cshtml";
}

<div class="row justify-content-between">
    <div class="col-lg-4 col-md-4 p-r-0 title-margin-right">
        <div class="page-header">
            <div class="page-title">
                <h1>Xin chào, <span class="fw-b fz-18">Admin</span></h1>
            </div>
        </div>
    </div>
    <!-- /# column -->
    <div class="col-lg-6 col-md-6 title-margin-left">
        <div class="page-header">
            <div class="page-title">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="NhapHang" asp-area="admin">Nhập hàng</a></li>
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="NhapHang" asp-area="admin">Danh sách</a></li>
                    <li class="breadcrumb-item active">Tạo mới</li>
                </ol>
            </div>
        </div>
    </div>
    <!-- /# column -->
</div>

<div class="container-fluid card overflow-scroll">
    <div class="row">
        <div class="col-lg-12">
            <div class="horizontal-form-elements">
                <form id="form-horizontal">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-2 col-md-12 control-label">Tên gạo</label>
                                <div class="col-sm-10">
                                    <input type="text" required class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-2 col-md-12 control-label">Số lượng</label>
                                <div class="col-sm-10">
                                    <input type="text" required class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-2 col-md-12 control-label">Ngày nhập</label>
                                <div class="col-sm-10">
                                    <input type="date" required class="form-control">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
    <div class="row justify-content-end">
        <div class="col-3">
            <a asp-action="Index" asp-controller="NhapHang" asp-area="admin" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-arrow-left fw-b"></i> Quay về danh sách
            </a>
        </div>
        <div class="col-3">
            <button type="submit" form="form-horizontal" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-save fw-b"></i> Lưu
            </button>
        </div>
    </div>
</div>

DoAn/Areas/admin/Views/NhapHang/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/admin/Views/Share/_layoutAdmin.cshtml";
}

<div class="row justify-content-between">
    <div class="col-lg-4 col-md-4 p-r-0 title-margin-right">
        <div class="page-header">
            <div class="page-title">
                <h1>Xin chào, <span class="fw-b fz-18">Admin</span></h1>
            </div>
        </div>
    </div>
    <!-- /# column -->
    <div class="col-lg-6 col-md-6 title-margin-left">
        <div class="page-header">
            <div class="page-title">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Nhập hàng</a></li>
                    <li class="breadcrumb-item active">Danh sách</li>
                </ol>
            </div>
        </div>
    </div>
    <!-- /# column -->
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="data_table card" style="overflow-x: scroll">
                <a asp-action="Create" asp-controller="NhapHang" asp-area="admin" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                    <i class="ti-plus fw-b"></i> Tạo mới
                </a>
                <!-- Modal HTML -->
                <table id="example" class="table table-striped table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>ID</th>
                            <th>Tên gạo</th>
                            <th>Số lượng nhập</th>
                            <th>Ngày nhập</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            for (int i = 0; i <= 1; i++)
                            {
                                <div id="myModal-@i" class="modal fade">
                                    <div class="modal-dialog modal-confirm">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <div class="icon-box">
                                                    <i class="ti-close"></i>
                                                </div>
                                                <h4 class="modal-title">Bạn chắc chắn chứ?</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                <p>Bạn có chắc muốn xóa các bản ghi này không? Thao tác này không thể hoàn tác</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-info" data-dismiss="modal">Hủy bỏ</button>
                                                <button type="button" class="btn btn-danger">Xóa</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <tr>
                                    <td>1</td>
                                    <td>Gạo 1</td>
                                    <td>111</td>
                                    <td>11/11/2011</td>
                                    <td>
                                        <div class="d-flex justify-content-end">
                                            <a asp-action="Update" asp-controller="NhapHang"><i class="ti-pencil button-add"></i></a>
                                            <a href="#myModal-@i" data-toggle="modal"><i class="ti-trash button-remove"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

DoAn/Areas/admin/Views/NhapHang/Update.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/admin/Views/Share/_layoutAdmin.cshtml";
}

<div class="row justify-content-between">
    <div class="col-lg-4 col-md-4 p-r-0 title-margin-right">
        <div class="page-header">
            <div class="page-title">
                <h1>Xin chào, <span class="fw-b fz-18">Admin</span></h1>
            </div>
        </div>
    </div>
    <!-- /# column -->
    <div class="col-lg-6 col-md-6 title-margin-left">
        <div class="page-header">
            <div class="page-title">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="NhapHang" asp-area="admin">Nhập hàng</a></li>
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="NhapHang" asp-area="admin">Danh sách</a></li>
                    <li class="breadcrumb-item active">Sửa
            </div>
        </div>
    </div>
    <!-- /# column -->
</div>

<div class="container-fluid card overflow-scroll">
    <div class="row">
        <div class="col-lg-12">
            <div class="horizontal-form-elements">
                <form id="form-horizontal">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-2 col-md-12 control-label">Tên gạo</label>
                                <div class="col-sm-10">
                                    <input type="text" required class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-2 col-md-12 control-label">Số lượng</label>
                                <div class="col-sm-10">
                                    <input type="text" required class="form-control">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-2 col-md-12 control-label">Ngày nhập</label>
                                <div class="col-sm-10">
                                    <input type="date" required class="form-control">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
    <div class="row justify-content-end">
        <div class="col-3">
            <a asp-action="Index" asp-controller="NhapHang" asp-area="admin" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-arrow-left fw-b"></i> Quay về danh sách
            </a>
        </div>
        <div class="col-3">
            <button type="submit" form="form-horizontal" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-save fw-b"></i> Lưu
            </button>
        </div>
    </div>
</div>