DoAn/Areas/admin/Models/QuyCachDongGoi.cs
namespace DoAn.Areas.admin.Models
{
    public class QuyCachDongGoi
    {
        public int Id { get; set; }
        public int khoiLuong { get; set; }
        public ICollection<DongGoi> dongGois { get; set; }
    }
}

DoAn/Areas/admin/Controllers/QuyCachDongGoiController.cs
using DoAn.Areas.admin.Data;
using DoAn.Areas.admin.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace DoAn.Areas.admin.Controllers
{
    [Area("admin")]
    public class QuyCachDongGoiController : Controller
    {
        private readonly KhoGaoDbContext context;
        private readonly IToastNotification toast;
        public QuyCachDongGoiController(KhoGaoDbContext context, IToastNotification toast)
        {
            this.context = context;
            this.toast = toast;
        }

        public async Task<IActionResult> Index()
        {
            var quycach = await context.QuyCachDongGoi.AsNoTracking().ToListAsync();
            return View(quycach);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(QuyCachDongGoi quyc)
        {
            context.Add(quyc);
            await context.SaveChangesAsync();
            toast.AddSuccessToastMessage("Thêm thành công", new ToastrOptions { Title = "Thông báo" });
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int id)
        {
            var quycach = await context.QuyCachDongGoi.Where(x => x.Id == id).AsNoTracking().FirstOrDefaultAsync();
            return View(quycach);
        }
        [HttpPost]
        public async Task<IActionResult> Update(QuyCachDongGoi quyc)
        {
            context.Update(quyc);
            await context.SaveChangesAsync();
            toast.AddSuccessToastMessage("Sửa thành công", new ToastrOptions { Title = "Thông báo" });
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            QuyCachDongGoi quyc= new QuyCachDongGoi { Id= id };
            try
            {
                context.Remove(quyc);
                await context.SaveChangesAsync();
                toast.AddSuccessToastMessage("Xóa thành công", new ToastrOptions { Title = "Thông báo" });
            }
            catch 
            {
                toast.AddErrorToastMessage("Không thể xóa bảng ghi này", new ToastrOptions { Title = "Thông báo" });
            }
            return RedirectToAction("Index");
        }
    }
}

DoAn/Areas/admin/Views/QuyCachDongGoi/Create.cshtml
@model DoAn.Areas.admin.Models.QuyCachDongGoi
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/admin/Views/Share/_layoutAdmin.cshtml";
}

<div class="row justify-content-between">
    <div class="col-lg-4 col-md-4 p-r-0 title-margin-right">
        <div class="page-header">
            <div class="page-title">
                <h1>Xin chào, <span class="fw-b fz-18">Admin</span></h1>
            </div>
        </div>
    </div>
    <!-- /# column -->
    <div class="col-lg-6 col-md-6 title-margin-left">
        <div class="page-header">
            <div class="page-title">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="QuyCachDongGoi" asp-area="admin">Quy cách đóng gói</a></li>
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="QuyCachDongGoi" asp-area="admin">Danh sách</a></li>
                    <li class="breadcrumb-item active">Tạo mới</li>
                </ol>
            </div>
        </div>
    </div>
    <!-- /# column -->
</div>

<div class="container-fluid card overflow-scroll">
    <div class="row">
        <div class="col-lg-12">
            <div class="horizontal-form-elements">
                <form method="post" id="form-horizontal">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-2 col-md-12 control-label">Khối lượng</label>
                                <div class="col-sm-10">
                                    <input type="number" asp-for="khoiLuong" required class="form-control">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
    <div class="row justify-content-end">
        <div class="col-3">
            <a asp-action="Index" asp-controller="QuyCachDongGoi" asp-area="admin" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-arrow-left fw-b"></i> Quay về danh sách
            </a>
        </div>
        <div class="col-3">
            <button type="submit" form="form-horizontal" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-save fw-b"></i> Lưu
            </button>
        </div>
    </div>
</div>

DoAn/Areas/admin/Views/QuyCachDongGoi/Index.cshtml
@model IEnumerable<DoAn.Areas.admin.Models.QuyCachDongGoi>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/admin/Views/Share/_layoutAdmin.cshtml";
}

<div class="row justify-content-between">
    <div class="col-lg-4 col-md-4 p-r-0 title-margin-right">
        <div class="page-header">
            <div class="page-title">
                <h1>Xin chào, <span class="fw-b fz-18">Admin</span></h1>
            </div>
        </div>
    </div>
    <!-- /# column -->
    <div class="col-lg-6 col-md-6 title-margin-left">
        <div class="page-header">
            <div class="page-title">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Quy cách đóng gói</a></li>
                    <li class="breadcrumb-item active">Danh sách</li>
                </ol>
            </div>
        </div>
    </div>
    <!-- /# column -->
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="data_table card" style="overflow-x: scroll">
                <a asp-action="Create" asp-controller="QuyCachDongGoi" asp-area="admin" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                    <i class="ti-plus fw-b"></i> Tạo mới
                </a>
                <!-- Modal HTML -->
                <table id="example" class="table table-striped table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>ID</th>
                            <th>khối lượng (kg)</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            foreach (var quycach in Model)
                            {
                                <div id="myModal-@quycach.Id" class="modal fade">
                                    <div class="modal-dialog modal-confirm">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <div class="icon-box">
                                                    <i class="ti-close"></i>
                                                </div>
                                                <h4 class="modal-title">Bạn chắc chắn chứ?</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                <p>Bạn có chắc muốn xóa các bản ghi này không? Thao tác này không thể hoàn tác</p>
                                            </div>
                                            <form method="post" asp-action="Delete" asp-route-id = "@quycach.Id">
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-info" data-dismiss="modal">Hủy bỏ</button>
                                                    <button type="submit" class="btn btn-danger">Xóa</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <tr>
                                    <td>@quycach.Id</td>
                                    <td>@quycach.khoiLuong</td>
                                    <td>
                                        <div class="d-flex justify-content-end">
                                            <a asp-action="Update" asp-controller="QuyCachDongGoi" asp-route-id ="@quycach.Id"><i class="ti-pencil button-add"></i></a>
                                            <a href="#myModal-@quycach.Id" data-toggle="modal"><i class="ti-trash button-remove"></i></a>
                                        </div>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

DoAn/Areas/admin/Views/QuyCachDongGoi/Update.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/admin/Views/Share/_layoutAdmin.cshtml";
}
@model DoAn.Areas.admin.Models.QuyCachDongGoi
<div class="row justify-content-between">
    <div class="col-lg-4 col-md-4 p-r-0 title-margin-right">
        <div class="page-header">
            <div class="page-title">
                <h1>Xin chào, <span class="fw-b fz-18">Admin</span></h1>
            </div>
        </div>
    </div>
    <!-- /# column -->
    <div class="col-lg-6 col-md-6 title-margin-left">
        <div class="page-header">
            <div class="page-title">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="QuyCachDongGoi" asp-area="admin">Quy cách đóng gói</a></li>
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="QuyCachDongGoi" asp-area="admin">Danh sách</a></li>
                    <li class="breadcrumb-item active">Sửa</li>
                </ol>
            </div>
        </div>
    </div>
    <!-- /# column -->
</div>

<<div class="container-fluid card overflow-scroll">
    <div class="row">
        <div class="col-lg-12">
            <div class="horizontal-form-elements">
                <form method="post" id="form-horizontal">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-2 col-md-12 control-label">Khối lượng</label>
                                <div class="col-sm-10">
                                    <input type="number" asp-for="khoiLuong" required class="form-control">
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
    <div class="row justify-content-end">
        <div class="col-3">
            <a asp-action="Index" asp-controller="QuyCachDongGoi" asp-area="admin" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-arrow-left fw-b"></i> Quay về danh sách
            </a>
        </div>
        <div class="col-3">
            <button type="submit" form="form-horizontal" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-save fw-b"></i> Lưu
            </button>
        </div>
    </div>
</div>