DoAn/Areas/admin/Models/DanhGia.cs
namespace DoAn.Areas.admin.Models
{
    public class DanhGia
    {
        public int Id { get; set; }
        public int IDGao { get; set; }
        public int IDTaiKhoan { get; set; }
        public string noiDung { get; set; }
        public int soSao { get; set; }
        public DateTime thoiGian { get; set; }
        public Gao gao { get; set; }
        public TaiKhoan taiKhoan { get; set; }
    }
}

DoAn/Areas/admin/Controllers/DanhGiaController.cs
using DoAn.Areas.admin.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace DoAn.Areas.admin.Controllers
{
    [Area("admin")]
    public class DanhGiaController : Controller
    {
        private readonly KhoGaoDbContext context;
        private readonly IToastNotification toast;
        public DanhGiaController(KhoGaoDbContext context, IToastNotification toast)
        {
            this.context = context;
            this.toast = toast;
        }

        public async Task<IActionResult> Index()
        {
            var danhgia = await context.DanhGia.Include(x => x.gao).Include(x => x.taiKhoan).AsNoTracking().ToListAsync();
            return View(danhgia);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var danhGia = await context.DanhGia.Where(x => x.Id == id).Include(x => x.taiKhoan).AsNoTracking().FirstOrDefaultAsync();
            if(danhGia.taiKhoan.loaiTaiKhoan == 0)
            {
                var gao = await context.Gao.Where(x => x.Id == danhGia.IDGao).AsNoTracking().FirstOrDefaultAsync();
                var dg = await context.DanhGia.Include(x => x.taiKhoan).Where(x => x.IDGao == gao.Id && x.taiKhoan.loaiTaiKhoan == 0).AsNoTracking().ToListAsync();
                int sum = 0;
                foreach(var x in dg)
                {
                    sum += x.soSao;
                }
                gao.soSao = sum/ 5;
                context.Update(gao);
                await context.SaveChangesAsync();
            }
            context.Remove(danhGia);
            await context.SaveChangesAsync();
            toast.AddSuccessToastMessage("Xóa thành công", new ToastrOptions { Title = "Thông báo" });
            return RedirectToAction("Index");
        }
    }
}

DoAn/Areas/admin/Views/DanhGia/Create.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/admin/Views/Share/_layoutAdmin.cshtml";
}
<div class="row justify-content-between">
    <div class="col-lg-4 col-md-4 p-r-0 title-margin-right">
        <div class="page-header">
            <div class="page-title">
                <h1>Xin chào, <span class="fw-b fz-18">Admin</span></h1>
            </div>
        </div>
    </div>
    <!-- /# column -->
    <div class="col-lg-6 col-md-6 title-margin-left">
        <div class="page-header">
            <div class="page-title">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="DanhGia" asp-area="admin">Đánh giá</a></li>
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="DanhGia" asp-area="admin">Danh sách</a></li>
                    <li class="breadcrumb-item active">Tạo mới</li>
                </ol>
            </div>
        </div>
    </div>
    <!-- /# column -->
</div>

<div class="container-fluid card overflow-scroll">
    <div class="row">
        <div class="col-lg-12">
            <div class="horizontal-form-elements">
                <form id="form-horizontal">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="tk" class="col-sm-2 col-md-12 control-label">Tên gạo</label>
                                <div class="col-sm-10">
                                    <select class="form-control appe-auto" id="tk">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="tk" class="col-sm-2 col-md-12 control-label">Tài khoản</label>
                                <div class="col-sm-10">
                                    <select class="form-control appe-auto" id="tk">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-2 col-md-12 control-label">Nội dung</label>
                                <div class="col-sm-10">
                                    <textarea required class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="tk" class="col-sm-2 col-md-12 control-label">Số sao</label>
                                <div class="col-sm-10">
                                    <select class="form-control appe-auto" id="tk">
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
    <div class="row justify-content-end">
        <div class="col-3">
            <a asp-action="Index" asp-controller="DanhGia" asp-area="admin" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-arrow-left fw-b"></i> Quay về danh sách
            </a>
        </div>
        <div class="col-3">
            <button type="submit" form="form-horizontal" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-save fw-b"></i> Lưu
            </button>
        </div>
    </div>
</div>

DoAn/Areas/admin/Views/DanhGia/Index.cshtml
@model IEnumerable<DoAn.Areas.admin.Models.DanhGia>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/admin/Views/Share/_layoutAdmin.cshtml";
}

<div class="row justify-content-between">
    <div class="col-lg-4 col-md-4 p-r-0 title-margin-right">
        <div class="page-header">
            <div class="page-title">
                <h1>Xin chào, <span class="fw-b fz-18">Admin</span></h1>
            </div>
        </div>
    </div>
    <!-- /# column -->
    <div class="col-lg-6 col-md-6 title-margin-left">
        <div class="page-header">
            <div class="page-title">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Đánh giá</a></li>
                    <li class="breadcrumb-item active">Danh sách</li>
                </ol>
            </div>
        </div>
    </div>
    <!-- /# column -->
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="data_table card" style="overflow-x: scroll">
                <!-- Modal HTML -->
                <table id="example" class="table table-striped table-bordered">
                    <thead class="table-dark">
                        <tr>
                            <th>ID</th>
                            <th>Gạo</th>
                            <th>Khách hàng</th>
                            <th>Nội dung</th>
                            <th>Số sao</th>
                            <th>Thao tác</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int i = 0;
                            foreach (var item in Model)
                            {
                                <div id="myModal-@i" class="modal fade">
                                    <div class="modal-dialog modal-confirm">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <div class="icon-box">
                                                    <i class="ti-close"></i>
                                                </div>
                                                <h4 class="modal-title">Bạn chắc chắn chứ?</h4>
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                <p>Bạn có chắc muốn xóa các bản ghi này không? Thao tác này không thể hoàn tác</p>
                                            </div>
                                            <form method="post" asp-action="Delete" asp-route-id = "@item.Id">
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-info" data-dismiss="modal">Hủy bỏ</button>
                                                    <button type="submit" class="btn btn-danger">Xóa</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.gao.tenGao</td>
                                    <td>@item.taiKhoan.taiKhoan</td>
                                    <td>@item.noiDung</td>
                                    <td>@item.soSao sao</td>
                                    <td>
                                        <div class="d-flex justify-content-end">
                                            <a href="#myModal-@i" data-toggle="modal"><i class="ti-trash button-remove"></i></a>
                                        </div>
                                    </td>
                                </tr>
                                <span style="display: none">@(i++)</span>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

DoAn/Areas/admin/Views/DanhGia/Update.cshtml
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/admin/Views/Share/_layoutAdmin.cshtml";
}
<div class="row justify-content-between">
    <div class="col-lg-4 col-md-4 p-r-0 title-margin-right">
        <div class="page-header">
            <div class="page-title">
                <h1>Xin chào, <span class="fw-b fz-18">Admin</span></h1>
            </div>
        </div>
    </div>
    <!-- /# column -->
    <div class="col-lg-6 col-md-6 title-margin-left">
        <div class="page-header">
            <div class="page-title">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="DanhGia" asp-area="admin">Đánh giá</a></li>
                    <li class="breadcrumb-item"><a asp-action="Index" asp-controller="DanhGia" asp-area="admin">Danh sách</a></li>
                    <li class="breadcrumb-item active">Sửa</li>
                </ol>
            </div>
        </div>
    </div>
    <!-- /# column -->
</div>

<div class="container-fluid card overflow-scroll">
    <div class="row">
        <div class="col-lg-12">
            <div class="horizontal-form-elements">
                <form id="form-horizontal">
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="tk" class="col-sm-2 col-md-12 control-label">Tên gạo</label>
                                <div class="col-sm-10">
                                    <select class="form-control appe-auto" >
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="tk" class="col-sm-2 col-md-12 control-label">Tài khoản</label>
                                <div class="col-sm-10">
                                    <select class="form-control appe-auto" >
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="col-sm-2 col-md-12 control-label">Nội dung</label>
                                <div class="col-sm-10">
                                    <textarea required class="form-control"></textarea>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="tk" class="col-sm-2 col-md-12 control-label">Số sao</label>
                                <div class="col-sm-10">
                                    <select class="form-control appe-auto" >
                                        <option>1</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <!-- /# card -->
        </div>
        <!-- /# column -->
    </div>
    <div class="row justify-content-end">
        <div class="col-3">
            <a asp-action="Index" asp-controller="DanhGia" asp-area="admin" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-arrow-left fw-b"></i> Quay về danh sách
            </a>
        </div>
        <div class="col-3">
            <button type="submit" form="form-horizontal" class="btn btn-lg btn-success btn-block waves-effect waves-light">
                <i class="ti-save fw-b"></i> Lưu
            </button>
        </div>
    </div>
</div>